version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/create-github-app-token"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
